<a href="https://colab.research.google.com/github/Athitiya00/multivariate/blob/main/Funtion_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Function

```python
def function_name(_Input_) :
    do_something with _Input_ to get _Output_ 
    return  _Output_
 ```

funcion มีส่วนสำคัญทั้งหมด 4 ส่วน

1. บอก python ว่าเราจะเขียนฟังก์ชั่น ชื่ออะไร def function_name(): (ขาดไม่ได้)
2. กำหนดตัวแปรที่จะเป็น input (ขาดได้)
3. ส่วนประมวลผล do_something whth input to get Output (ขาดไม่ได้)
4. ส่วน output return output (ขาดได้)

เราใช้ เว้นวรรค (indent) เพื่อบอกขอบเขตของ code

##สร้างฟังก์ชั่น

In [ ]:
def print_name(name,surname,ID) :
     st = f'ชื่อ {name} นามสกุล {surname} ID {ID}'
     return st
print('outside function')

outside function


##การเรียกใช้ฟังก์ชั่น

In [ ]:
print_name('อาธิติยา', 'ธรรมวงษา', '623021058-0')

'ชื่อ อาธิติยา นามสกุล ธรรมวงษา ID 623021058-0'

In [ ]:
output_string = print_name('อาธิติยา', 'ธรรมวงษา', '623021058-0')
print(output_string)

ชื่อ อาธิติยา นามสกุล ธรรมวงษา ID 623021058-0


ฟังก์ชั่นไม่จำเป็นต้องมี Output

In [ ]:
def print_name2(surname,ID,name) :
     st = f'ชื่อ {name} นามสกุล {surname} รหัส {ID}'
     print(st)

In [ ]:
print_name2('อาธิติยา', 'ธรรมวงษา', '623021058-0')

ชื่อ 623021058-0 นามสกุล อาธิติยา รหัส ธรรมวงษา


In [ ]:
op2 = print_name2('อาธิติยา', 'ธรรมวงษา', '623021058-0')

ชื่อ 623021058-0 นามสกุล อาธิติยา รหัส ธรรมวงษา


In [ ]:
print(op2)

None


ฟังก์ชั่นไม่จำเป็นต้องมี input

In [ ]:
def Pi():
     return 3.14159265359

In [ ]:
#คำนวณพื้นที่วงกลมที่มีขนาดเส้นผ่านศูนย์กลางเท่ากับ 3
Pi()*(1.5**2)

7.0685834705775

In [ ]:
def print_my_name():
     print('อาธิติยา ธรรมวงษา ID 623021058-0')

In [ ]:
print_my_name()

อาธิติยา ธรรมวงษา ID 623021058-0


**1.input ของ function ใน python มีสองแบบ input ที่จำเป็นต้องใส่ กับ input ที่ไม่จำเป็นต้องใส (มีค่า default)**

**2.เราต้องเรียง input ที่จำเป็นต้องใส่ขึ้นก่อน**

In [ ]:
def print_2lines_default(name, surname, ID, grade='F'):
    st = f'ชื่อ {name} นามสกุล {surname} รหัส {ID}'
    print(st)
    st2 = f'เกรดวิชา Multivariate >>> {grade}'
    print(st2)

In [ ]:
print_2lines_default('อาธิติยา', 'ธรรมวงษา', '623021058-0')

ชื่อ อาธิติยา นามสกุล ธรรมวงษา รหัส 623021058-0
เกรดวิชา Multivariate >>> F


In [ ]:
print_2lines_default('อาธิติยา', 'ธรรมวงษา', '623021058-0','A')

ชื่อ อาธิติยา นามสกุล ธรรมวงษา รหัส 623021058-0
เกรดวิชา Multivariate >>> A


In [ ]:
print_name2(name='อาธิติยา', surname='ธรรมวงษา', ID='623021058-0')

ชื่อ อาธิติยา นามสกุล ธรรมวงษา รหัส 623021058-0


## HW3 ให้เขียน function คำนวณจำนวนวินาทีจากเวลาต่อไปนี้

'14-15-31'

'13-00-01'

'05-49-44'

'00-00-16'

และ print ให้สวยงาม

In [ ]:
def function_q(times):
  q = f'เวลา {times}'
  print(q)
  times_sp = times.split('-')
  answer = int(times_sp[0])*3600 + int(times_sp[1])*60 + int(times_sp[2])
  print(f'คำนวณเป็นจำนวนวินาทีได้เท่ากับ {answer} วินาที')

In [ ]:
function_q('14-15-13')

เวลา 14-15-13
คำนวณเป็นจำนวนวินาทีได้เท่ากับ 51313 วินาที


In [ ]:
function_q('13-00-01')

เวลา 13-00-01
คำนวณเป็นจำนวนวินาทีได้เท่ากับ 46801 วินาที


In [ ]:
function_q('05-49-44')

เวลา 05-49-44
คำนวณเป็นจำนวนวินาทีได้เท่ากับ 20984 วินาที


In [ ]:
function_q('00-00-16')

เวลา 00-00-16
คำนวณเป็นจำนวนวินาทีได้เท่ากับ 16 วินาที


##Numpy

Numpy -> package สำหรับจัดการกับ Array ที่เป็นตัวเลข (Matrix)

Num + py -> Number-numerical + python

การใช้ package
1. ```import ```  ```ชื่อ package ``` #เรียกใช้ package
2. ```ชื่อ package.ชื่อฟังก์ชั่น ``` #เรียกใช้ function

In [10]:
import numpy

สร้าง numpy array

In [11]:
mat_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


ชี้ค่า numpy array

In [12]:
mat_ex1[1,1]  #[แถว,หลัก]

0.1

ถ้าไม่มี numpy array

In [13]:
list_ex1 = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
print(list_ex1)

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]


In [14]:
list_ex1[1,1]

TypeError: ignored

In [15]:
list_ex1[1][1]

0.1

In [16]:
print(list_ex1)
a = list_ex1[1]
print(a)
print(a[1])

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]
[9.1, 0.1, 0.3]
0.1


Matrix Operations

data 2 แบบ -> matrix (2D array), scalar (ตัวเลขค่าคงที่)

In [17]:
mat_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)
mat_ex2 = numpy.array([[2,3.7,5.9],[91,1.5,7.3]])
print(mat_ex2)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]


## บวกกับลบ matrix เอาตัวเลขตำแหน่งเดียวกันมาบวกหรือลบกัน
(หน้าตาของ matrix ต้องเหมือนกัน)

In [18]:
mat_ex0 = numpy.array([[1,2],[3,4]])
print(mat_ex0)

[[1 2]
 [3 4]]


In [19]:
mat_ex3 = mat_ex1 + mat_ex2
print(mat_ex3)
mat_ex4 = mat_ex1 - mat_ex2
print(mat_ex4)

[[  7.2   6.7  10.4]
 [100.1   1.6   7.6]]
[[  3.2  -0.7  -1.4]
 [-81.9  -1.4  -7. ]]


In [20]:
mat_ex1 + mat_ex0

ValueError: ignored

การตรวจสอบขนาดของ matrix

In [21]:
mat_ex3.shape

(2, 3)

In [22]:
mat_ex3.shape[0]

2

## คูณ matrix

In [23]:
print(mat_ex1)
print(mat_ex1.shape)
print(mat_ex2)
print(mat_ex2.shape)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
(2, 3)
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]
(2, 3)


In [24]:
mat_ex1 * mat_ex2

array([[1.040e+01, 1.110e+01, 2.655e+01],
       [8.281e+02, 1.500e-01, 2.190e+00]])

## การคูณ matrix (แถวคูณหลัก)
(หลักของ Matrix ตัวข้างหน้า ต้องเท่ากับแถวของ Matrix ตัวข้างหลัง)

(AAA,x) . (x,ZZZ) = (AAA,ZZZ)

In [25]:
numpy.dot(mat_ex1,mat_ex2)

ValueError: ignored

In [26]:
print(mat_ex1)
print(mat_ex1.shape)
print(mat_ex2)
print(mat_ex2.shape)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
(2, 3)
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]
(2, 3)


# Transpose กลับแถวเป็นหลักกลับหลักเป็นแถว

```matrix.T```

In [27]:
print(mat_ex2)
print(mat_ex2.shape)

[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]
(2, 3)


In [28]:
print(mat_ex2.T)
print(mat_ex2.T.shape)

[[ 2.  91. ]
 [ 3.7  1.5]
 [ 5.9  7.3]]
(3, 2)


In [29]:
numpy.dot(mat_ex1,mat_ex2.T) #(2,3).(3,2)

array([[ 48.05, 510.55],
       [ 20.34, 830.44]])

In [30]:
numpy.dot(mat_ex1.T,mat_ex2) #(3,2).(2,3) = (3,3)

array([[838.5 ,  32.89,  97.11],
       [ 15.1 ,  11.25,  18.43],
       [ 36.3 ,  17.1 ,  28.74]])

HW4 อธิบายการหา Determinant และ Inverse matrix (รูป และ คำอธิบาย)

~pandas~